### ISSUE TITLE
Color by label

### ISSUE THREAD

**Issue by mstaniak** [ModelOriented/ingredients#10]
What should be the default behavior? Compare the four options below. IMO the last plot looks best, but even if coloring by default is a bad idea, I think the third plot should have drwhy_theme colors.

Example:

library("DALEX")
library("ingredients")
titanic <- na.omit(titanic)
model_titanic_glm <- glm(survived == "yes" ~ gender + age + fare,
                         data = titanic, family = "binomial")
explain_titanic_glm <- explain(model_titanic_glm,
                               data = titanic[,-9],
                               y = titanic$survived == "yes")
ale_glm <- accumulated_dependency(explain_titanic_glm, N = 50, variables = "age")
pdp_glm <- variable_response(explain_titanic_glm, variable = "age")

library("randomForest")
model_titanic_rf <- randomForest(survived ~ gender + age + class + embarked +
                                   fare + sibsp + parch,  data = titanic)
explain_titanic_rf <- explain(model_titanic_rf,
                              data = titanic[,-9],
                              y = titanic$survived)
ale_rf <- accumulated_dependency(explain_titanic_rf)
pdp_rf <- variable_response(explain_titanic_rf, variable = "age")

plot(ale_glm, ale_rf)
plot(ale_glm, ale_rf) +
  theme_drwhy()
plot(ale_glm, ale_rf, color = "_label_") +
  theme_drwhy()
plot(pdp_glm, pdp_rf)

**Comment by pbiecek** [comment]
Thanks,
These are drwhy colors (scale is set to theme_drwhy_colors(nlabels)), but for two classes they are just two shades of blue

Default coloring in accumulated_dependency is good idea
