### ISSUE TITLE
why does aggregate_profiles have a "variable_type" input argument?

### ISSUE THREAD

**Issue by harell** [ModelOriented/ingredients#100]
I'm trying to generate parietal plots via `ingredients:::partial_dependency` for a dataset that has both numeric and non-numeric variables.

At the moment, I'm using a workaround to accomplish that because `aggregate_profiles` accepts either `variable_type="numerical"` or `variable_type=categorical` but no both.

What is the reason behind this restriction?

If there is none, I'll be happy to refactor `aggregate_profiles` in a way that will eliminate `variable_type`.

Would you consider to merge such a solution?

Thanks

**Comment by harell** [comment]
I see a potential explanation. 

This is because `aggregated_profiles_partial` binds `_x_`; 
Combining numeric and non-numeric variable coerces all values to "character", or results with an error.

I'll think of a solution and post it back

**Comment by harell** [comment]
The following function plots both "numerical" and "categorical" variables.
I include the code for people coming here from searching the topic

```
# Workaround --------------------------------------------------------------
plot_partial_dependency <- function(x, ...){
    args <- tryCatch(as.list(...), error = function(e) list())
    args <- append(args, list(x=x))
    variables <- args$variables
    if(is.null(variables)) variables <- colnames(args$x$data)
    
    partial_dependency <- function(args) do.call(ingredients::partial_dependency, args)
    
    gg_objects <- list()
    for(variable in variables){
        args <- purrr::list_modify(args, variables = variable)
        suppressMessages(
            gg_objects[[variable]] <-
                args %>% partial_dependency() %>% plot() +
                ggplot2::ggtitle(label = "") +
                ggplot2::theme_bw() +
                ggplot2::theme(legend.position = "none")
        )
    }
    
    n <- length(gg_objects)
    ncol <- ceiling(sqrt(n)); nrow <- floor(sqrt(n))
    label <- "Partial Dependency Plot"
    gtable <- do.call(gridExtra::grid.arrange, c(gg_objects, ncol = ncol, nrow = nrow, top = label, as.table = FALSE))
    
    return(gtable)
}

# Setup -------------------------------------------------------------------
data <- mtcars %>% dplyr::mutate(vs = factor(vs, levels = 0:1, labels = c("V-shaped", "straight")))
explainer <- DALEX::explain(model = lm(mpg ~., data),
                            data = data %>% dplyr::select(-mpg),
                            y = data %>% dplyr::select(mpg) %>% unlist())

```

```
## Original function only shows 'numeric' variables
ingredients::partial_dependency(explainer) %>% plot()
```
The originl function only show numeric variables. It omits `vs` becuase it is categorical

![image](https://user-images.githubusercontent.com/7226303/73711234-148bcb00-476b-11ea-8272-bf8fe32fed7a.png)

```
## Workaround shows all variables
plot_partial_dependency(explainer) %>% plot()
```
The workaround does show `vs` 

![image](https://user-images.githubusercontent.com/7226303/73711185-ea3a0d80-476a-11ea-945a-ea0660f14d09.png)

**Comment by pbiecek** [comment]
Thanks, the problem is exactly as you described it. 
In a single ggplot2 you can have series of plots after faceting, but they must have on the x axis either a categorical variable or continuous variables. But not both together.

I like this hack in which you have used gridExtra. 
The side effect is that y scales are different in different panels and also the y label is repeated multiple times. 
I've tried the patchwork package but then i hit similar problem.

Currently I'm using facets in ceteris paribus, partial dependence and local accumulated differences. 
Maybe the gridExtra is the way to go. Will check. thanks.
