### ISSUE TITLE
Automated variable grouping in Variable Importance

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ingredients#109]
Export [group_variables](https://modeloriented.github.io/DALEXtra/reference/group_variables.html) function and promote the `explainer %>% group_variables %>% variable_importance` pipeline to deal with correlated variables.

**Comment by hbaniecki** [comment]
Additionally: use `group_variables` to color these groups on the 'not grouped' variable importance plot.

**Comment by pbiecek** [comment]
the `group_variables` will be moved to https://github.com/kasiapekala/aspectImportance/
(which will be named triplot).

Let's move this issue to `aspectImportance` package

**Comment by hbaniecki** [comment]
I wanted to add `group_variables` to this package as well (it's not complicated). The problem is that it only works for `numerical` variables, so it would be hard to plug into `variable_importance` for now.

**Comment by hbaniecki** [comment]
I guess that it will be a part of `triplot` package.
