### ISSUE TITLE
n_sample -> N 

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ingredients#113]
Following https://github.com/ModelOriented/DALEX/issues/175 I want to deprecate `n_samples`.
Additionally, @pbiecek why is this sampling using `replace`?
https://github.com/ModelOriented/ingredients/blob/9f8f82f05ddb87e4abf2fb20846f097113522a33/R/feature_importance.R#L196

No such behaviour here:
https://github.com/ModelOriented/ingredients/blob/9f8f82f05ddb87e4abf2fb20846f097113522a33/R/partial_dependence.R#L109

**Comment by pbiecek** [comment]
`replace = TRUE` means that `nrow(data)` can be smaller than n_sample (because some observations ill be reused).
On average it shall not make any difference if we use sampling with/without replacement.
