### ISSUE TITLE
Default loss_function for feature_importance

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/ingredients#117]
Once DALEX 1.2.2 [hits master](https://github.com/ModelOriented/DALEX/pull/210), it will support multiclass classification. I suggest small rework for `feature_importance.explainer()` so function checks the `explainer$model_info$type` and uses `loss_cross_entropy` or `loss_one_minus_auc` accordingly to `multiclass` and `classification` types.

**Comment by pbiecek** [comment]
once this is added, 
let's force user to use specific versions fo DALEX (>=1.2.2) and ingredients (>=1.2.2) to keep consistency between sets of packages

**Comment by hbaniecki** [comment]
Good idea, but this enforcement will only work one way (meaning `DALEX 1.2.2` will force `ingredients 1.2.2`).

**Comment by pbiecek** [comment]
added to ver 1.3
