### ISSUE TITLE
color argument in plot.aggregated profiles doesn't work

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ingredients#122]
The behaviour of the `color` argument in `plot.aggregated_profiles` is bugged. 
```r
library('ingredients')
library("DALEX")

model_titanic_glm <- glm(survived ~ gender + age + fare,
                         data = titanic_imputed, family = "binomial")

explain_titanic_glm <- explain(model_titanic_glm,
                               data = titanic_imputed[,-8],
                               y = titanic_imputed[,8],
                               verbose = FALSE)

pdp_rf_p <- partial_dependence(explain_titanic_glm, N = 50)

plot(pdp_rf_p, color = "_label_")
plot(pdp_rf_p, color = "gender") # error
plot(pdp_rf_p, color = "_ids_") # different error
plot(pdp_rf_p, color = "_vname_") # yet another different error

```
If the name of the variable is passed, then it always yields an error, because no categorical & numerical variables are possible in one `AP` object; even more, `AP` object doesn't have columns that could be named with the potential variable name.

The only possible `color` value (other than `_label_`) is `_groups_` (if `AP` was made using the `groups` parameter). 
Edit: Even the `_groups_` parameter is worse to use when plotting multiple `AP` objects. This makes `_label_` the only viable option.
https://github.com/ModelOriented/ingredients/blob/6a5fbbaed920f695d4246ffb8c29031fa9655b7a/R/plot_aggregated_profiles.R#L97-L110

**Comment by pbiecek** [comment]
@hbaniecki  Is it really a bug?
It is not clear for me how `plot(pdp_rf_p, color = "gender")` shall behave if PDP profiles are calculated without grouping.

The desired effect can be obtained with 
```
 pdp_rf_p <- partial_dependence(explain_titanic_glm, N = 50, groups = "gender")
 plot(pdp_rf_p)
```
first calculated PDPs for groups and then plot them

**Comment by hbaniecki** [comment]
The point was that we can delete this argument and always use `color='_label_'`. Any other value of the `color` parameter makes little sense to me, since even when grouped, `color=_label_` is better than `color=_groups_`.

**Comment by pbiecek** [comment]
sometimes `color` may be useful,
for example if we have 2 models and 4 instances, then with the `color` argument user can decide if models shall be colored( `_label_`) or instances shall be colored( `_ids_`) or all curves shall have same fixed color (`color = "red"`)

**Comment by hbaniecki** [comment]
True, the 97 line of code got me offguard, because `color` can't be a variable, especially it shouldn't be `_vname_`.
https://github.com/ModelOriented/ingredients/blob/6a5fbbaed920f695d4246ffb8c29031fa9655b7a/R/plot_aggregated_profiles.R#L97

**Comment by pbiecek** [comment]
so, maybe it's about the documentation,
i've updated the doc for aggregate_profiles

**Comment by hbaniecki** [comment]
Sure. I guess that it could also be a `variable` when using `categorical x categorical`.
