### ISSUE TITLE
Ceteris Paribus profiles for sparse.model.matrix

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/ingredients#132]
Is it possible to create Ceteris Paribus explainers for explainers where `sparse.matrix.model` object data was passed? it was requested at https://github.com/ModelOriented/DALEX/issues/331.

Right now the problem seems to occur in this lapply https://github.com/ModelOriented/ingredients/blob/master/R/calculate_variable_profile.R#L28-L48

**Comment by hbaniecki** [comment]
Closing as this was previously closed in https://github.com/ModelOriented/DALEX/issues/331 and https://github.com/ModelOriented/DALEXtra/issues/60.
