### ISSUE TITLE
Add facet options to plots

### ISSUE THREAD

**Issue by leossbr** [ModelOriented/ingredients#136]
As of now 'ceteris paribus' plots regarding more than one variable only have the "free_y" option built-in. I think it'd be a good idea to allow the user to select how the facet will behave, be it "free_x", "free_y" or "free" as a ggplot output.

**Comment by pbiecek** [comment]
hi, 
thanks for pointing out this issue, 
The `facet_wrap` can be added to the result of plot() function and this will override the default settings.
