### ISSUE TITLE
Effect sizes

### ISSUE THREAD

**Issue by asheetal** [ModelOriented/ingredients#144]
I want to model the effect sizes of predictors. My goal is that along with unexplained effects the sum total must be 100%. And then represent them (grouped) in a sort of pie chart. 

Any guidance how should I approach this problem?

**Comment by hbaniecki** [comment]
Hi @asheetal, am I assuming correctly that you work primarily with statistical models? Reading through your problem, you might want to check out the [effectsize](https://github.com/easystats/effectsize) package.

**Comment by asheetal** [comment]
Thanks @hbaniecki for your reply. I saw this package works with bayesian models as well. Can This work with xgboost models also?

**Comment by hbaniecki** [comment]
I have no clue, you might want to ask in the project's issues.
