### ISSUE TITLE
Joint Variable Importance 

### ISSUE THREAD

**Issue by kmatusz** [ModelOriented/ingredients#17]
In variable_importance It would be nice to be able to define a group of variables to be perturbed at once. This would be useful for example to assess group of features engineered from one underlying variable.

**Comment by pbiecek** [comment]
This will be a great feature and accualy it would be useful for both break_down and variable_importance.
We have it in the roadmap, but lacking of hands. 
If you are interested in the development of such feature that would be great.

**Comment by kmatusz** [comment]
Sure, I would be happy to contribute.

**Comment by pbiecek** [comment]
The permutation shall be done in blocks (not every variable independently).
so rather
```
  res <- sapply(variables, function(variables_set) {
    ndf <- sampled_data
    # sample variables in variables_set
    ndf[, variables_set] <- ndf[sample(1:nrow(ndf)), variables_set]

    predicted <- predict_function(x, ndf)
    loss_function(observed, predicted)
  })
```

**Comment by pbiecek** [comment]
added in  7ff7e35
