### ISSUE TITLE
aspect_importance function

### ISSUE THREAD

**Issue by kasiapekala** [ModelOriented/ingredients#30]
I've added experimental version of aspect importance function to forked repo. Fork contains new aspect_importance functions, vignette and tests.

[forked repo](https://github.com/KTHS/ingredients)

**Comment by pbiecek** [comment]
Looks great.
Few comments to discuss at our next meeting:

- coefficients from the linear model may be visually presented in a plot like this one: https://pbiecek.github.io/PM_VEE/shapley.html#example-titanic-2
- the implemented method is actually similar in spirit to https://pbiecek.github.io/PM_VEE/LIME.html so we may consider other name for this function (or alias like lime)
- in addition to lm model it would be nice to consider also LASSO models, then we may control number of  non-zero coefficients
- it would be nice to have an automated way for identification of aspects. Like clustering of features based on correlation between them. This will be super cool

**Comment by kasiapekala** [comment]
Fork is updated with following changes:

1. group_variables() is added (auto. features clustering)
2. temporary function is added that shows more info about features group (aspects) - if useful could be merged with aspect_importance() or with print.aspect_importance()
3. get_sample() method is updated as discussed
4. aspect_importance() now returns dataframe instead of lm object
5. plot.aspect_importance() is updated to show if coeff. are positive/negative (as in shapley example)
6. aspect_lime alias is added
7. tests and manual are updated
8. vignette is updated to demo new functions

ad 1/2
group_variables() works only for cont. variables
add_additional_information works for every dataframe with aspect_importance results, but shows correlation info only for aspects with cont. variables

Next steps:
- option to use LASSO model
- more tests with datsets and models

**Comment by pbiecek** [comment]
Thanks, 
IMHO `lime` is better than `aspect_lime`
apart of this, could you puch pull request? I'll recreate website with pkgdown

**Comment by pbiecek** [comment]
@kasiapekala shall we close this issue?

**Comment by kasiapekala** [comment]
Yes.
