### ISSUE TITLE
ALE plot for discrete variables

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ingredients#40]

**Comment by pbiecek** [comment]
Plots are working now
https://modeloriented.github.io/ingredients/reference/aggregate_profiles.html
https://modeloriented.github.io/ingredients/reference/accumulated_dependency.html

**Comment by hbaniecki** [comment]
Add support for multiple explainers in D3

**Comment by pbiecek** [comment]
@hbaniecki shall we close this issue?
