### ISSUE TITLE
tests for aspect_importance

### ISSUE THREAD

**Issue by tkonopka** [ModelOriented/ingredients#41]
Running the test suite on my machine produces an error from one of the tests in file `test_aspect_importance.R`, line 57. I am confused because travis reports the package is building correctly. @kasiapekala, can you help? Thanks.

Here are some of the objects within the test.

`new_observation`

```
     construction.year surface floor no.rooms district
1002              1978     112     9        4  Mokotow
```

`aspect_importance_ap`

```
            aspects importance
5          district   279.6734
4             floor  -205.1207
2             space  -120.3610
3 construction.year   116.6933
```

**Comment by kasiapekala** [comment]
Thanks. Code indeed passes the test on travis and on my machine. But I see that the model returns different results here than expected. I will look into that.

**Comment by kasiapekala** [comment]
Could you please attached sessionInfo? Thank you in advance.

**Comment by kasiapekala** [comment]
Ok. Probably results posted above were generated on machine with R 3.5 or lower. Tests that passed were running on 3.6. I was able to reproduce above results after changing random number generator to "rounding".

While updating tests, I'll use RNGkind() function to control the type of generator used and to get the results to be the same regardless of R version.

**Comment by tkonopka** [comment]
Hi. Thanks for your help with this. 

Indeed. The result was using 3.5.1 and 3.5.2. (sessionInfo is probably no longer needed now).

Thanks again.

**Comment by tkonopka** [comment]
Following up on this - can confirm the effect goes on/off due to R versions 3.5/3.6. 

Do you have an update ready? I can submit a fix if it's ok with you for me to edit this file.

**Comment by kasiapekala** [comment]
Thank you for confirming that the R version is the source of the trouble.

I will be updating the whole set of aspect_importance tests during the next couple of days, so the fix for the generator issue will be one of the updates. Nonetheless thanks for the offer.
