### ISSUE TITLE
bug in feature_importance when using variable groups and data as a matrix

### ISSUE THREAD

**Issue by tkonopka** [ModelOriented/ingredients#42]
Currently `feature_importance` works with a non-null list of `variable_groups` when `data` is a data frame, but not when `data` is a matrix. Some models (xgboost) require a matrix, so it is not possible to work around this on the user side. It would be great to make the `variable_groups` work with matrices as well.

I can adjust the code and add a test.

**Comment by pbiecek** [comment]
Thanks. It would be great if you can add this enhancement along with some tests.
