### ISSUE TITLE
'theme_drwhy_colors()' is now deprecated

### ISSUE THREAD

**Issue by AnnaGierlak** [ModelOriented/ingredients#60]
Hi,

If I want to plot aggregated profiles, e.g.:
```
library(DALEX)
library(ingredients)
titanic <- na.omit(titanic)
model_titanic_glm <- glm(survived == "yes" ~ gender + age + fare,
                         data = titanic, family = "binomial")
explain_titanic_glm <- explain(model_titanic_glm,
                               data = titanic[,-9],
                               y = titanic$survived == "yes",
                               verbose = FALSE)
pdp_rf_p <- partial_dependency(explain_titanic_glm, N = 50)
plot(pdp_rf_p)
```
I get the following message:
Warning message:
Please note that 'theme_drwhy_colors()' is now deprecated, it is better to use 'colors_discrete_drwhy()' instead. 
I think it is beacuse of the changes in the latest version of `DALEX` package. In `plot.aggregated_profiles_explainer` function `theme_drwhy_colors` occurs twice.

**Comment by pbiecek** [comment]
Try the latest version of ingredients.
