### ISSUE TITLE
missing factorMerger

### ISSUE THREAD

**Issue by ciberger** [ModelOriented/ingredients#71]
Hi!

I've noticed that the function factorMerger used to analyse categorical/factor variables was deprecated, and the proposed function does not provide the same results. Is there a reason for this?

many thanks!

**Comment by pbiecek** [comment]
Thanks. 

There was a problem with consistency for feature effects. 
In DALEX for continuous variables we have partial dependency profiles, while factorMerger was used for categorical variables. These two are different approaches.

In ingredients partial dependency profiles are extended to works for categorical variables. So results can be read in a similar way for continuous and categorical variables.

factorMerger will be added again as a tools for feature extraction/auto-feature engineering. A prototype is now in the rSAFE package. 
Some day it will be also ported to ingredients.

**Comment by ciberger** [comment]
Hi! 

thanks for the quick reply.

I previously noticed what you mentioned that factorMerger functionality is now covered by the partial dependency profile. I found valuable the clustering visualization from factorMerger, but it's good to know that this was migrated to the rSAFE package, so thanks for that tip. 

Appreciate the effort you are putting into this project. 

Keep it up!
