### ISSUE TITLE
Ceteris Paribus - Ranger in multiclass problem throws error

### ISSUE THREAD

**Issue by WojciechKretowicz** [ModelOriented/ingredients#75]
```
model = ranger(Species~., data=iris)
explainer = explain(model, iris[,-5], iris[,5])
ceteris_paribus(explainer, iris[1:5,-5], iris[1:5,5])
```

`Error in if (ncol(pred) == 2) { : argument is of length zero`

**Comment by pbiecek** [comment]
@WojciechKretowicz 
thanks, actually the problem is in the `ranger` model. 
It needs to be trained with `probability = TRUE`, otherwise `predict` will not return numeric score

With
```
 model = ranger(Species~., data=iris, probability = TRUE)
```
these lines are working ok.

The explainer shall suggest this problem and actually it is doing so with 
```
 -> predicted values  :  the predict_function returns an error when executed (  WARNING  ) 
```

**Comment by WojciechKretowicz** [comment]
Ok, thank you. I will be more careful next time.
