### ISSUE TITLE
Add pseudocode for ALE plots 

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/ingredients#81]

**Comment by pbiecek** [comment]
Here is the pseudocode:

Input:

```
Top profiles    : 
       gender age            class    embarked    fare sibsp parch     _yhat_
515    female  45              2nd Southampton 10.1000     0     0 0.09490975
515.1    male  45              2nd Southampton 10.1000     0     0 0.85053814
604    female  17              3rd Southampton  7.1701     1     0 0.11321362
604.1    male  17              3rd Southampton  7.1701     1     0 0.47411576
1430   female  25 engineering crew Southampton  0.0000     0     0 0.24005121
1430.1   male  25 engineering crew Southampton  0.0000     0     0 0.69052740
       _vname_ _ids_      _label_
515     gender   515 randomForest
515.1   gender   515 randomForest
604     gender   604 randomForest
604.1   gender   604 randomForest
1430    gender  1430 randomForest
1430.1  gender  1430 randomForest
```

Algorithm for CD (for ALE is similar):

1. For each row in the Ceteris Paribus description add additional column `_original_` that will keep information about the corresponding observation (with index `_ids_`). CP profile shall know the observation that generates the profile.

2. Split the input into chunks for separate variables/ models
    ("_vname_", "_label_"). Process each chunk independently.

3. For every point in the CP profile calculate distance from the generator `_original_`. Use this distance as a weight. Use Gaussian kernel weighting for continuous variables and characteristic function for categorical variables.

4. Split the current chunk into groups associated with a single value for the variable of interest (split by `_x_`)

5. Do the weighted averaging. This way profiles with `_original_` closer to current `_x_` will have larger contribution.


If there are `groups`, then the splitting is with this additional variable

**Comment by pbiecek** [comment]
@hbaniecki @WojciechKretowicz let me know if this pseudocode is too simplified

Corresponding formulas are also here: https://pbiecek.github.io/PM_VEE/accumulatedLocalProfiles.html#conditional-dependency-profile

**Comment by WojciechKretowicz** [comment]
It works for me. Every split is described with its purpose. Thank you!

**Comment by hbaniecki** [comment]
Looks good!
