### ISSUE TITLE
Differently spaced plots using facet_col.

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/ingredients#83]
[ggforce](https://github.com/tidyverse/ggplot2/issues/2933)

**Comment by pbiecek** [comment]
@hbaniecki are we going to do this in foreseeable future?
if not, let's close it

**Comment by hbaniecki** [comment]
The idea was to space the `pdp/cp` bar plots evenly (this is an issue when one facet has 2 bars, while the other has 10). It would add some dependencies to the `ingredients` package, see:

```r
devtools::install_github("DominikRafacz/deepdep")
library(deepdep)
dd <- deepdep('ingredients', depth=4)
plot_dependencies(dd)
dd2 <- deepdep('ggforce', depth=4)
plot_dependencies(dd2)
```

What would be more beneficial for the users, is using the `patchwork` package to display both `numerical` and `categorical` variables in the `cp.plot` and remove the `variable_type` parameter (planning on doing so in the python implementation).

If both are out of scope, then we can close the issue.

**Comment by pbiecek** [comment]
both features looks super interesting, but both will infect `ingredients`, `DALEX` and all dependent packages with heavy dependencies of `patchwork` and `ggforce`

maybe an alternative solution would be to add these features to the `DALEXtra` package, which already has heavy dependencies (or other package with prettier plots for DrWhy).

**Comment by hbaniecki** [comment]
`patchwork` seem to add zero dependencies (besides `gtable`).
![image](https://user-images.githubusercontent.com/32574004/88716577-88f26600-d11f-11ea-897f-84dced69fb12.png)

**Comment by pbiecek** [comment]
except `patchwork` itself
but if this solves the problem of displaying both numerical and categorical variables in the cp.plot then it's worth adding
