### ISSUE TITLE
Plots Ceteris Paribus Profiles in D3 not working

### ISSUE THREAD

**Issue by ggajardocea** [ModelOriented/ingredients#93]
When I try to run the [example](https://modeloriented.github.io/ingredients/reference/plotD3_ceteris_paribus.html#examples) for D3 plotting, I get the following error. Are there some changes in the functions that i have to be aware of?

Error:
`Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"`

**Comment by hbaniecki** [comment]
Hi! Can you paste sessionInfo()?

**Comment by pbiecek** [comment]
works for me 
`ingredients` v. 0.5
DALEX v. 0.5
R v. 3.6.1

**Comment by ggajardocea** [comment]
> sessionInfo()

R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.3.6.so

ingredients_0.4 
DALEX_0.4.9

**Comment by ggajardocea** [comment]
I think it must be either a problem with linux or with the version of ingredients, or well... both. It does not allows me to install ingredients_0.5.1 in Linux

On windows it works:

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default
other attached packages:
[1] r2d3_0.2.3          randomForest_4.6-14 ingredients_0.5.1   DALEX_0.5.0        
[5] shapper_0.1.2 
```

On Linux it does not

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.3.6.so

other attached packages:
[1] r2d3_0.2.3          randomForest_4.6-14 ingredients_0.5.0   DALEX_0.5.0        
[5] shapper_0.1.2 
```
